# travis does not get along with our default database.yml settings
<% if ENV['DB'].nil? || ENV['DB'] == 'postgres' %>
  test:
    username: postgres
<% elsif ENV['DB'] == 'mysql' %>
  test:
    username: ~
<% end %>
