postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
sqlite: &sqlite
  adapter: sqlite3
  database: ":memory:"
  timeout: 500
mysql: &mysql
  adapter: mysql2
  username: root
  encoding: utf8

development:
  database: join_a_squad_development
  <<: *<%= ENV['DB'] || 'postgres' %>
test:
  database: join_a_squad_test
  <<: *<%= ENV['DB'] || 'postgres' %>
production:
  database: join_a_squad_production
  <<: *<%= ENV['DB'] || 'postgres' %>
